### ISSUE TITLE
CALL JOB:SET_TCPON before TCPON  command

### ISSUE THREAD

**Issue by CagtayFabry** [barisccolak/Internship#18]
When a the `TCPON` command is called, the previous line **must** be a call to `CALL JOB:SET_TCPON` with the same argument number in both cases.

Example (OK):
```
CALL JOB:SET_TCPON ARGF1
TCPON TL#(1)
```

Example (error, the `JOB:SET_TCPON` is called with input 33, the `TCPON` command is called with argument 22. These numbers must match):
```
CALL JOB:SET_TCPON ARGF33
TCPON TL#(22)
```

Example (error, the line before `TCPON` is not `CALL JOB:SET_TCPON`):
```
TIMER T=0.50
TCPON TL#(1)
```

**Comment by barisccolak** [comment]
Buggy behaviour:

```
CALL JOB:SET_TCPON ARGF1
TCPON TL#(1)
CALL JOB:SET_TCPON ARGF33
TCPON TL#(22)
```

Delivers no error.
