### ISSUE TITLE
add a python package

### ISSUE THREAD

**Issue by CagtayFabry** [barisccolak/Internship#3]
create a python package ( e.g. `testmodule`) that can be imported using
```python
import testmodule
```

The module should include different functions (that don't have to do anything for now)

```python
from testmodule import function1
from testmodule import function2
from testmodule.sunmodule import function3
```

Some resources:
- https://python-packaging.readthedocs.io/en/latest/minimal.html
- https://realpython.com/python-modules-packages/

**Comment by barisccolak** [comment]
Closed issue.

**Comment by barisccolak** [comment]
Closed issue really.
